name: rf-pitr

on:
  workflow_dispatch:
    inputs:
      file_url:
        description: 'url'
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Download File
        run: |
          
          curl -L -o file.zip ${{ inputs.file_url }}
          
          FILE_NAME=$(basename ${{ inputs.file_url }})
          
      - name: Create Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          files: file.zip
          tag_name: "latest-mirror" 
          token: ${{ secrets.GITHUB_TOKEN }} 
